import { blockedCashEngine } from '../blockedCash/calculator'
import { PROJECT_BLOCKED_BY_CERTIFICATION } from '../blockedCash/sampleData'
import { collectionsEngine } from '../collections/calculator'
import { COLLECTIONS_SAMPLE_INPUT } from '../collections/sampleData'
import { liquidityEngine } from '../liquidity/calculator'
import { LIQUIDITY_SAMPLE_INPUT } from '../liquidity/sampleData'
import { morningBriefEngine } from '../morningBrief/morningBriefEngine'
import { MORNING_BRIEF_SAMPLE_INPUT } from '../morningBrief/sampleData'
import { treasuryEngine } from '../treasury/calculator'
import { TREASURY_SAMPLE_INPUT } from '../treasury/sampleData'
import type { Scenario, ScenarioSimulatorInput } from './types'

export const SCENARIO_SIMULATOR_SCENARIOS: Scenario[] = [
  {
    id: 'collections-plus-1cr',
    name: 'Collections +₹1 Cr',
    category: 'Collections',
    description: 'Collect an additional ₹1 Cr from committed customers.',
    cashImpactMinor: 10_000_000,
    runwayImpactDays: 3,
    collectionsGapImpactMinor: 10_000_000,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 2,
  },
  {
    id: 'collections-plus-5cr',
    name: 'Collections +₹5 Cr',
    category: 'Collections',
    description: 'Accelerate ₹5 Cr of forecast customer collections.',
    cashImpactMinor: 50_000_000,
    runwayImpactDays: 17,
    collectionsGapImpactMinor: 50_000_000,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 6,
  },
  {
    id: 'collections-plus-10cr',
    name: 'Collections +₹10 Cr',
    category: 'Collections',
    description: 'Accelerate ₹10 Cr of collections into the current horizon.',
    cashImpactMinor: 100_000_000,
    runwayImpactDays: 32,
    collectionsGapImpactMinor: 100_000_000,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 10,
  },
  {
    id: 'architect-certificate-approved',
    name: 'Architect Certificate Approved',
    category: 'Blocked Cash',
    description: 'Clear architect certification for RERA withdrawal eligibility.',
    cashImpactMinor: 30_000_000,
    runwayImpactDays: 9,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 30_000_000,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 5,
  },
  {
    id: 'ca-certificate-approved',
    name: 'CA Certificate Approved',
    category: 'Blocked Cash',
    description: 'Clear CA certification for RERA withdrawal eligibility.',
    cashImpactMinor: 30_000_000,
    runwayImpactDays: 9,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 30_000_000,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 5,
  },
  {
    id: 'escrow-withdrawal-approved',
    name: 'Escrow Withdrawal Approved',
    category: 'Blocked Cash',
    description: 'Approve controlled escrow release for deployable use.',
    cashImpactMinor: 15_000_000,
    runwayImpactDays: 5,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 15_000_000,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 3,
  },
  {
    id: 'increase-od-limit',
    name: 'Increase OD Limit',
    category: 'Borrowings',
    description: 'Increase short-term OD headroom for treasury flexibility.',
    cashImpactMinor: 50_000_000,
    runwayImpactDays: 7,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: -6,
    healthScoreImpact: 2,
  },
  {
    id: 'draw-dlod',
    name: 'Draw DLOD',
    category: 'Borrowings',
    description: 'Draw available DLOD to cover near-term payment timing.',
    cashImpactMinor: 100_000_000,
    runwayImpactDays: 14,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 8,
    healthScoreImpact: 1,
  },
  {
    id: 'sales-slower-10',
    name: '10% slower sales',
    category: 'Sales',
    description: 'Model a 10% reduction in expected sales-led collections.',
    cashImpactMinor: -25_000_000,
    runwayImpactDays: -6,
    collectionsGapImpactMinor: -25_000_000,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 2,
    healthScoreImpact: -4,
  },
  {
    id: 'sales-slower-20',
    name: '20% slower sales',
    category: 'Sales',
    description: 'Model a 20% reduction in expected sales-led collections.',
    cashImpactMinor: -50_000_000,
    runwayImpactDays: -12,
    collectionsGapImpactMinor: -50_000_000,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 4,
    healthScoreImpact: -8,
  },
  {
    id: 'real-estate-release-architect',
    name: 'Release Architect Certificate',
    category: 'Real Estate',
    description: 'Release architect certificate to unlock RERA withdrawal.',
    cashImpactMinor: 40_000_000,
    runwayImpactDays: 12,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 40_000_000,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 6,
  },
  {
    id: 'real-estate-release-ca',
    name: 'Release CA Certificate',
    category: 'Real Estate',
    description: 'Release CA certificate to complete withdrawal documentation.',
    cashImpactMinor: 40_000_000,
    runwayImpactDays: 12,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 40_000_000,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 6,
  },
  {
    id: 'real-estate-approve-rera-withdrawal',
    name: 'Approve RERA Withdrawal',
    category: 'Real Estate',
    description: 'Approve eligible RERA withdrawal for immediate liquidity.',
    cashImpactMinor: 100_000_000,
    runwayImpactDays: 28,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 100_000_000,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 9,
  },
  {
    id: 'real-estate-sbi-retail-disbursement',
    name: 'Receive SBI Retail Disbursement',
    category: 'Real Estate',
    description: 'Receive expected SBI retail loan disbursement from buyers.',
    cashImpactMinor: 75_000_000,
    runwayImpactDays: 21,
    collectionsGapImpactMinor: 75_000_000,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 7,
  },
  {
    id: 'real-estate-delay-contractor-payment',
    name: 'Delay Contractor Payment by 15 Days',
    category: 'Real Estate',
    description: 'Defer eligible contractor payout to preserve short-term cash.',
    cashImpactMinor: 45_000_000,
    runwayImpactDays: 15,
    collectionsGapImpactMinor: 0,
    blockedCashImpactMinor: 0,
    borrowingUtilizationImpact: 0,
    healthScoreImpact: 3,
  },
]

const treasury = treasuryEngine.evaluate(TREASURY_SAMPLE_INPUT)
const liquidity = liquidityEngine.evaluate(LIQUIDITY_SAMPLE_INPUT)
const collections = collectionsEngine.evaluate(COLLECTIONS_SAMPLE_INPUT)
const blockedCash = blockedCashEngine.evaluate(PROJECT_BLOCKED_BY_CERTIFICATION)
const morningBrief = morningBriefEngine.evaluate(MORNING_BRIEF_SAMPLE_INPUT)

export const SCENARIO_SIMULATOR_SAMPLE_INPUT: ScenarioSimulatorInput = {
  currency: treasury.output.deployableCash.currency,
  treasury,
  liquidity,
  collections,
  blockedCash,
  morningBrief,
  scenarios: SCENARIO_SIMULATOR_SCENARIOS,
}
