import type { Booking } from '../domain/entities/Booking'
import type { Unit } from '../domain/entities/Unit'
import { DEMO_CURRENCY } from './group'

export const DEMO_UNITS: Unit[] = [
  {
    id: 'unit-geeta-a-1204',
    projectId: 'project-geeta',
    phaseId: 'phase-geeta-a',
    unitNumber: 'A-1204',
    unitType: '3 BHK',
    status: 'booked',
    area: 1625,
    saleValue: { amountMinor: 18_500_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-geeta-b-0802',
    projectId: 'project-geeta',
    phaseId: 'phase-geeta-a',
    unitNumber: 'B-0802',
    unitType: '2 BHK',
    status: 'booked',
    area: 1275,
    saleValue: { amountMinor: 14_200_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-prakash-c-1501',
    projectId: 'project-prakash',
    phaseId: 'phase-prakash-a',
    unitNumber: 'C-1501',
    unitType: '3 BHK',
    status: 'booked',
    area: 1710,
    saleValue: { amountMinor: 20_800_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-prakash-d-0605',
    projectId: 'project-prakash',
    phaseId: 'phase-prakash-a',
    unitNumber: 'D-0605',
    unitType: '2 BHK',
    status: 'booked',
    area: 1180,
    saleValue: { amountMinor: 12_900_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-geeta-r-0201',
    projectId: 'project-geeta',
    phaseId: 'phase-geeta-a',
    unitNumber: 'R-0201',
    unitType: 'Retail',
    status: 'booked',
    area: 920,
    saleValue: { amountMinor: 24_000_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-forest-e-1103',
    projectId: 'project-forest',
    phaseId: 'phase-forest-a',
    unitNumber: 'E-1103',
    unitType: '3 BHK',
    status: 'booked',
    area: 1660,
    saleValue: { amountMinor: 19_600_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-prakash-a-1702',
    projectId: 'project-prakash',
    phaseId: 'phase-prakash-a',
    unitNumber: 'A-1702',
    unitType: '4 BHK',
    status: 'booked',
    area: 2210,
    saleValue: { amountMinor: 28_500_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'unit-forest-r-0104',
    projectId: 'project-forest',
    phaseId: 'phase-forest-a',
    unitNumber: 'R-0104',
    unitType: 'Retail',
    status: 'booked',
    area: 760,
    saleValue: { amountMinor: 16_800_000, currency: DEMO_CURRENCY },
  },
]

export const DEMO_BOOKINGS: Booking[] = [
  {
    id: 'booking-rohan-geeta-1204',
    projectId: 'project-geeta',
    unitId: 'unit-geeta-a-1204',
    customerId: 'customer-rohan-mehta',
    bookingDate: '2025-10-14T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 18_500_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-ananya-geeta-0802',
    projectId: 'project-geeta',
    unitId: 'unit-geeta-b-0802',
    customerId: 'customer-ananya-shah',
    bookingDate: '2025-11-02T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 14_200_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-vikram-prakash-1501',
    projectId: 'project-prakash',
    unitId: 'unit-prakash-c-1501',
    customerId: 'customer-vikram-rao',
    bookingDate: '2025-08-21T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 20_800_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-neha-prakash-0605',
    projectId: 'project-prakash',
    unitId: 'unit-prakash-d-0605',
    customerId: 'customer-neha-kapoor',
    bookingDate: '2026-01-17T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 12_900_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-kunal-geeta-retail',
    projectId: 'project-geeta',
    unitId: 'unit-geeta-r-0201',
    customerId: 'customer-kunal-industries',
    bookingDate: '2025-12-03T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 24_000_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-priya-forest-1103',
    projectId: 'project-forest',
    unitId: 'unit-forest-e-1103',
    customerId: 'customer-priya-nair',
    bookingDate: '2026-02-11T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 19_600_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-arjun-prakash-1702',
    projectId: 'project-prakash',
    unitId: 'unit-prakash-a-1702',
    customerId: 'customer-arjun-malhotra',
    bookingDate: '2025-09-05T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 28_500_000, currency: DEMO_CURRENCY },
  },
  {
    id: 'booking-sapphire-forest-retail',
    projectId: 'project-forest',
    unitId: 'unit-forest-r-0104',
    customerId: 'customer-sapphire-ventures',
    bookingDate: '2026-03-19T00:00:00.000Z',
    status: 'confirmed',
    agreementValue: { amountMinor: 16_800_000, currency: DEMO_CURRENCY },
  },
]
